(define-module (audio)
  #:use-module (rnrs bytevectors)
  #:use-module (ice-9 binary-ports)
  #:use-module (dsl)
  #:export (play sample-rate))

(define sample-rate 44100)

(define (segundos->amostras s)
  (inexact->exact (round (* s sample-rate))))

(define (criar-buffer duracao-total)
  (make-vector (segundos->amostras duracao-total) 0.0))

(define (escrever-nota! buffer inicio fim freq volume)
  (let* ((amostra-ini (segundos->amostras inicio))
         (amostra-fim (min (vector-length buffer) (segundos->amostras fim))))
    (let loop ((i amostra-ini))
      (when (< i amostra-fim)
        (let* ((t (/ (- i amostra-ini) (exact->inexact sample-rate)))
               (env (min 1.0 (* 20 (min t (- (/ (- amostra-fim amostra-ini) sample-rate) t)))))
               (valor (* volume env (sin (* 2 3.14159265 freq t)))))
          (vector-set! buffer i (+ (vector-ref buffer i) valor))
          (loop (+ i 1)))))))

(define (normalizar! buffer)
  (let ((pico (apply max (map abs (vector->list buffer)))))
    (when (> pico 1.0)
      (let loop ((i 0))
        (when (< i (vector-length buffer))
          (vector-set! buffer i (/ (vector-ref buffer i) pico))
          (loop (+ i 1)))))))

(define (escrever-wav! buffer caminho)
  (let* ((n (vector-length buffer))
         (bytes-por-amostra 2)
         (data-size (* n bytes-por-amostra))
         (bv (make-bytevector (+ 44 data-size) 0)))
    (bytevector-u8-set! bv 0 (char->integer #\R)) (bytevector-u8-set! bv 1 (char->integer #\I))
    (bytevector-u8-set! bv 2 (char->integer #\F)) (bytevector-u8-set! bv 3 (char->integer #\F))
    (bytevector-u32-set! bv 4 (+ 36 data-size) (endianness little))
    (bytevector-u8-set! bv 8 (char->integer #\W)) (bytevector-u8-set! bv 9 (char->integer #\A))
    (bytevector-u8-set! bv 10 (char->integer #\V)) (bytevector-u8-set! bv 11 (char->integer #\E))
    (bytevector-u8-set! bv 12 (char->integer #\f)) (bytevector-u8-set! bv 13 (char->integer #\m))
    (bytevector-u8-set! bv 14 (char->integer #\t)) (bytevector-u8-set! bv 15 (char->integer #\space))
    (bytevector-u32-set! bv 16 16 (endianness little))
    (bytevector-u16-set! bv 20 1 (endianness little))
    (bytevector-u16-set! bv 22 1 (endianness little))
    (bytevector-u32-set! bv 24 sample-rate (endianness little))
    (bytevector-u32-set! bv 28 (* sample-rate bytes-por-amostra) (endianness little))
    (bytevector-u16-set! bv 32 bytes-por-amostra (endianness little))
    (bytevector-u16-set! bv 34 16 (endianness little))
    (bytevector-u8-set! bv 36 (char->integer #\d)) (bytevector-u8-set! bv 37 (char->integer #\a))
    (bytevector-u8-set! bv 38 (char->integer #\t)) (bytevector-u8-set! bv 39 (char->integer #\a))
    (bytevector-u32-set! bv 40 data-size (endianness little))
    (let loop ((i 0))
      (when (< i n)
        (let ((amostra (inexact->exact (round (* 32000 (vector-ref buffer i))))))
          (bytevector-s16-set! bv (+ 44 (* i 2)) amostra (endianness little)))
        (loop (+ i 1))))
    (call-with-output-file caminho
      (lambda (porta) (put-bytevector porta bv)))))

;; `nota->freq` é injetada de fora (via `notas.scm`), então
;; `play` recebe a tabela de frequências como argumento extra,
;; mantendo `audio.scm` desacoplado de qual sistema de afinação
;; está sendo usado.
(define-syntax play
  (syntax-rules ()
    ((_ nome bpm nota->freq-fn)
     (let* ((processado (processar nome))
            (duracao-total (apply max (map cadr processado)))
            (buffer (criar-buffer (+ duracao-total 0.2))))
       (for-each
        (lambda (grupo)
          (let ((ini (car grupo)) (fim (cadr grupo))
                (notas (caddr grupo)) (vol (cadddr grupo)))
            (for-each
             (lambda (nota-simbolo)
               (escrever-nota! buffer ini fim (nota->freq-fn nota-simbolo) vol))
             notas)))
        processado)
       (normalizar! buffer)
       (escrever-wav! buffer "saida.wav")
       (system* "play" "-q" "saida.wav")))))